// Metamask
export const CONNECT_TO_WALLET = "CONNECT_TO_WALLET";
export const ONBOARDING = "ONBOARDING";
export const CONNECT_FAILED = "CONNECT_FAILED";
export const LOGOUT = "LOGOUT";

// ETH
export const NETWORK_CORRECT = "NETWORK_CORRECT";
export const NETWORK_FAIL = "NETWORK_FAIL";

// GHOSTS
export const GHOSTS_SUCCESS = "GHOSTS_SUCCESS";
export const MARKETPLACE_SUCCESS = "MARKETPLACE_SUCCESS";
export const TRANSFER_SUCCESS = "TRANSFER_SUCCESS";

export const LISTING_CANCELED = "LISTING_CANCELED";
export const GHOST_LISTED = "GHOST_LISTED";
export const GHOST_EDITED = "GHOST_EDITED";
export const GHOST_PURCHASED = "GHOST_PURCHASED";

// DIALOG
export const LIST_GHOST = "LIST_GHOST";
export const CANCEL_GHOST = "CANCEL_GHOST";
export const EDIT_GHOST = "EDIT_GHOST";
export const PURCHASE_GHOST = "PURCHASE_GHOST";
export const CLOSE_DIALOG = "CLOSE_DIALOG";

// STATE
export const CLEAR_STATE = "CLEAR_STATE";

// ERRORS

export const GENERAL_ERROR = "GENERAL_ERROR";
export const DIALOG_ERROR = "DIALOG_ERROR";
export const LIST_ERROR = "LIST_ERROR";
export const EDIT_ERROR = "EDIT_ERROR";
export const CANCEL_ERROR = "CANCEL_ERROR";
export const PURCHASE_ERROR = "PURCHASE_ERROR";
export const MARKETPLACE_ERROR = "MARKETPLACE_ERROR";
export const TRANSFER_ERROR = "TRANSFER_ERROR";
export const GHOSTS_ERROR = "GHOSTS_ERROR";

// PAGINATION
export const CHANGE_PAGE = "CHANGE_PAGE";

// FILTERS
export const FILTER_BY_LISTING = "FILTER_BY_LISTING";
export const SET_PRICE_RANGE = "SET_PRICE_RANGE";
export const SORT_ITEMS_BY_PRICE = "SORT_ITEMS_BY_PRICE";
export const FILTER_COMPLETE = "FILTER_COMPLETE";
export const SET_FILTER_OPTIONS = "SET_FILTER_OPTIONS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
