export default [
	{
		id: 0,
		collection: "Official Game_NFT 1",
		cardName: "The Last Game",
		price: 0.25,
		time: "1 minute ago",
		bid: "0.20 HBARS",
		image: "/img/1.png",
	},
	{
		id: 1,
		collection: "Official Game_NFT 2",
		cardName: "The Last Game",
		price: 0.26,
		time: "4 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/2.png",
	},
	{
		id: 2,
		collection: "Official Game_NFT 3",
		cardName: "Donkey Kong",
		price: 1,
		time: "4 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/3.png",
	},
	{
		id: 3,
		collection: "Official Game_NFT 4",
		cardName: "Super Mario",
		price: 0.5,
		time: "6 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/4.png",
	},
	{
		id: 4,
		collection: "Official Game_NFT 5",
		cardName: "GTA",
		price: 3,
		time: "6 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/5.png",
	},
	{
		id: 5,
		collection: "Official Game_NFT 6",
		cardName: "Star Fox",
		price: 0.6,
		time: "10 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/6.png",
	},
	{
		id: 6,
		collection: "Official Game_NFT 7",
		cardName: "Legend of Zelda",
		price: 5,
		time: "11 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/7.png",
	},
	{
		id: 7,
		collection: "Official Game_NFT 8",
		cardName: "Hitman",
		price: 0.2,
		time: "13 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/8.png",
	},
	{
		id: 8,
		collection: "Official Game_NFT 9",
		cardName: "NFS",
		price: 0.25,
		time: "13 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/9.png",
	},
	{
		id: 9,
		collection: "Official Game_NFT 10",
		cardName: "Mario Kart",
		price: 2,
		time: "15 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/10.png",
	},
	{
		id: 10,
		collection: "Official Game_NFT 11",
		cardName: "Assassin's Creed",
		price: 0.26,
		time: "16 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/11.png",
	},
	{
		id: 11,
		collection: "Official Game_NFT 12",
		cardName: "Metroid",
		price: 0.9,
		time: "18 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/12.png",
	},
	{
		id: 12,
		collection: "Official Game_NFT 13",
		cardName: "Super Smash Bros",
		price: 0.05,
		time: "20 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/13.png",
	},
	{
		id: 13,
		collection: "Official Game_NFT 14",
		cardName: "Call of Duty",
		price: 2.05,
		time: "21 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/14.png",
	},
	{
		id: 14,
		collection: "Official Game_NFT 15",
		cardName: "Wolfenstein",
		price: 3,
		time: "22 minutes ago",
		bid: "0.20 HBARS",
		image: "/img/15.png",
	},
];
