export default [
	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},

	{
		id: 0,
		totalStaked: "Total Staked",
		value: "Total USD Value",
		myStaked: "My Staked",
		balance: "Balance",
		revards: "Revards",
		amount: "0",
		price: "$0",
		key: "0 KEY",
	},
];
